### ISSUE TITLE
Support for multiple destinations

### ISSUE THREAD

**Issue by irimiab** [kronometrix/avmet#1]
We need to support multiple destinations in the "avmet" gate.

**Comment by irimiab** [comment]
Implemented in the latest version.
The file `app/conf/config.lua` now has this section:
```
local kronometrix = {
    {
        host = "127.0.0.1",
        port = 80,
        path = "/api/private/send_data"
    },
    {
        host = "79.134.105.183",
        port = 80,
        path = "/api/private/send_data"
    }
}
```

The `host` field supports only IPs; to support also domains, this needs to run on NginX 1.11.3 or newer and the directive `resolver` needs to be used in the `stream` context, in `nginx.conf`
http://nginx.org/en/docs/stream/ngx_stream_core_module.html#resolver

**Comment by sparvu** [comment]
Ok good point. I will need to make a new gate package to test. We need to upgrade the gate pkg since what we are using is the expwrimental demo version.

**Comment by irimiab** [comment]
Ok

**Comment by sparvu** [comment]
here latest: http://www.kronometrix.org/pkgs/freebsd/kavmet-1.0.4-freebsd10.3-amd64.txz

**Comment by irimiab** [comment]
This is done, can be closed
